string mode  # "encode_text" or "encode_alpha_image"
sensor_msgs/Image rgb_img
sensor_msgs/Image[] alpha_masks
string text
---
float32[] aclip_fts  # 扁平化存储每个实例的clip特征，512维浮点数
uint16 aclip_ft_dim  # 每个实例特征的维度
